name: CD

on:
  push:
    branches:
      - blazium
      - blazium-dev
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login

      - name: Build Docker image
        run: |
          docker build \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:latest \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.sha }} \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.ref_name }} \
            .

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:latest
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.sha }}
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.ref_name }}

      - name: Get Python version
        id: pythonv
        run: |
          echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_OUTPUT

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.pythonv.outputs.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          path: .venv

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libcairo2-dev
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Build EPUB
        run: |
          source .venv/bin/activate
          make epub

      - name: Build PDF
        run: |
          source .venv/bin/activate
          sphinx-build -b pdf . _build/pdf

      - name: Create GitHub Release
        id: createRelease
        uses: ./.github/actions/create-github-release
        with:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_PAT }}
          OWNER: blazium-games
          REPO: blazium-docs
          TARGET_COMMIT: ${{ github.sha }}
          TAG_NAME: docs-${{ github.ref_name }}-${{ github.sha }}
          NAME: Documentation - ${{ github.ref_name }}
          DRAFT: "false"
          PRERELEASE: "false"
          GENERATE_RELEASE_NOTES: "true"
          DEBUG: "true"

      - name: Upload assets to GitHub release
        uses: ./.github/actions/upload-github-release
        with:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_PAT }}
          UPLOAD_URL: ${{ steps.createRelease.outputs.upload_url }}
          FILES: |
            ${{ github.workspace }}/_build/epub/BlaziumEngine.epub
            ${{ github.workspace }}/_build/pdf/BlaziumEngine.pdf
          DEBUG: "true"
