name: CD

on:
  push:
    branches:
      - blazium
      - blazium-dev
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: 
        group: release-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean Container Registry
        run: |
          mkdir -p ~/.docker
          echo "${{ secrets.DO_DOCKER_JSON }}" > ~/.docker/config.json

      - name: Build Docker image
        run: |
          docker build \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:latest \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.sha }} \
            -t registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.ref_name }} \
            .

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:latest
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.sha }}
          docker push registry.digitalocean.com/blazium-registry/blazium-docs:${{ github.ref_name }}

      - name: Get Python version
        id: pythonv
        run: |
          echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_OUTPUT

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.pythonv.outputs.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          path: .venv

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Build EPUB
        run: |
          source .venv/bin/activate
          make epub

      - name: Build PDF
        run: |
          source .venv/bin/activate
          sphinx-build -b pdf . _build/pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Documentation - ${{ github.ref_name }}
          tag_name: docs-${{ github.ref_name }}-${{ github.sha }}
          files: |
            _build/epub/BlaziumEngine.epub
            _build/pdf/BlaziumEngine.pdf
